### ISSUE TITLE
Unable to Render Icons Using Ligatures

### ISSUE THREAD

**Issue by ohitsdylan** [phosphor-icons/phosphor-icons#12]
I loaded in the Phosphor icons using the unpkg script and am unable to render any icons using ligatures.

I've tested in Firefox, Chrome, and Edge, just to be sure, and they all show the text only, never the icon.
I added an icon using the `<i>` element and the `ph-` class to make sure the font was loading, and this appears without issue.

I see a issue from this year that mentions that the author was able to get ligatures working, so I'm a little confused here. Is there anything more I need than what is provided in the example in the README?

My brief HTML test document looks like this:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script async src="https://unpkg.com/phosphor-icons"></script>
</head>
<body>
    <p style="font-family: Phosphor;">sword-fill</p>
    <i class="ph-cube"></i>
</body>
</html>
```

And the result is this:
![image](https://user-images.githubusercontent.com/55002846/207148498-2062783a-5167-48c5-99d9-e417384f579e.png)

I loaded in the Google Material Icon set to make sure that nothing was misconfigured in the browser somehow, and those ligatures work as they should.

**Comment by nyoroko** [comment]
I faced the same problem.
[v1.4.1 Release note](https://github.com/phosphor-icons/phosphor-icons/releases/tag/v1.4.1) says,

> Due to limitations with our tools, our icon font no longer supports ligatures, for the time being. Use the unicode codepoints, or class names provided on our site if in a web context. We're looking for a solution to this, and hope to have one soon.

So I decided to use the unicode codepoints.

**Comment by ohitsdylan** [comment]
Ah, thanks for that link! I'll close this issue, then.

**Comment by rektdeckard** [comment]
We'll be adding ligatures back in soon 👍
