### ISSUE TITLE
Invalid size in some icons

### ISSUE THREAD

**Issue by cyberalien** [phosphor-icons/phosphor-icons#2]
I guess all icons are supposed to be 256 x 256, but many have slightly different size:

bold/chat-bold: 256.00098 x 256.00098
bold/chat-centered-bold: 256.00098 x 256.00098
bold/chat-centered-dots-bold: 256.00098 x 256.00098
bold/chat-centered-text-bold: 256.00098 x 256.00098
bold/chat-dots-bold: 256.00098 x 256.00098
bold/chat-text-bold: 256.00098 x 256.00098
bold/chats-bold: 256.00098 x 256.00098
bold/copy-bold: 255.99316 x 255.99316
bold/copy-simple-bold: 255.99316 x 255.99316
bold/crop-bold: 255.99316 x 255.99316
bold/eraser-bold: 256.00098 x 256
bold/faders-bold: 256.00098 x 256.00098
bold/gear-bold: 256.00098 x 256.00098
bold/gear-six-bold: 256.00098 x 256.00098
bold/intersect-bold: 256.00098 x 256.00098
bold/magnifying-glass-minus-bold: 256.00098 x 256.00098
bold/magnifying-glass-bold: 256.00098 x 256.00098
bold/magnifying-glass-plus-bold: 256.00098 x 256.00098
bold/phosphor-logo-bold: 256 x 256.00004
bold/sliders-bold: 256.00098 x 256.00098
duotone/chat-centered-duotone: 256.00098 x 256.00098
duotone/chat-centered-dots-duotone: 256.00098 x 256.00098
duotone/chat-centered-text-duotone: 256.00098 x 256.00098
duotone/chat-dots-duotone: 256.00098 x 256.00098
duotone/chat-duotone: 256.00098 x 256.00098
duotone/chat-text-duotone: 256.00098 x 256.00098
duotone/chats-duotone: 256.00098 x 256.00098
duotone/copy-duotone: 255.99316 x 255.99316
duotone/copy-simple-duotone: 255.99316 x 255.99316
duotone/crop-duotone: 255.99316 x 255.99316
duotone/eraser-duotone: 256.00098 x 256
duotone/faders-duotone: 256.00098 x 256.00098
duotone/gear-duotone: 256.00098 x 256.00098
duotone/gear-six-duotone: 256.00098 x 256.00098
duotone/intersect-duotone: 256.00098 x 256.00098
duotone/magnifying-glass-duotone: 256.00098 x 256.00098
duotone/magnifying-glass-minus-duotone: 256.00098 x 256.00098
duotone/magnifying-glass-plus-duotone: 256.00098 x 256.00098
duotone/phosphor-logo-duotone: 256 x 256.00004
duotone/sliders-duotone: 256.00098 x 256.00098
fill/chat-centered-fill: 256.00098 x 256.00098
fill/chat-centered-dots-fill: 256.00098 x 256.00098
fill/chat-centered-text-fill: 256.00098 x 256.00098
fill/chat-dots-fill: 256.00098 x 256.00098
fill/chat-fill: 256.00098 x 256.00098
fill/chat-text-fill: 256.00098 x 256.00098
fill/chats-fill: 256.00098 x 256.00098
fill/copy-fill: 255.99316 x 255.99316
fill/copy-simple-fill: 255.99316 x 255.99316
fill/crop-fill: 255.99316 x 255.99316
fill/eraser-fill: 256.00098 x 256
fill/faders-fill: 256.00098 x 256.00098
fill/gear-fill: 256.00098 x 256.00098
fill/gear-six-fill: 256.00098 x 256.00098
fill/intersect-fill: 256.00098 x 256.00098
fill/magnifying-glass-fill: 256.00098 x 256.00098
fill/magnifying-glass-minus-fill: 256.00098 x 256.00098
fill/magnifying-glass-plus-fill: 256.00098 x 256.00098
fill/phosphor-logo-fill: 256 x 256.00004
fill/sliders-fill: 256.00098 x 256.00098
light/chat-centered-dots-light: 256.00098 x 256.00098
light/chat-centered-light: 256.00098 x 256.00098
light/chat-centered-text-light: 256.00098 x 256.00098
light/chat-dots-light: 256.00098 x 256.00098
light/chat-light: 256.00098 x 256.00098
light/chat-text-light: 256.00098 x 256.00098
light/chats-light: 256.00098 x 256.00098
light/copy-light: 255.99316 x 255.99316
light/copy-simple-light: 255.99316 x 255.99316
light/crop-light: 255.99316 x 255.99316
light/eraser-light: 256.00098 x 256
light/faders-light: 256.00098 x 256.00098
light/gear-light: 256.00098 x 256.00098
light/gear-six-light: 256.00098 x 256.00098
light/intersect-light: 256.00098 x 256.00098
light/magnifying-glass-light: 256.00098 x 256.00098
light/magnifying-glass-minus-light: 256.00098 x 256.00098
light/magnifying-glass-plus-light: 256.00098 x 256.00098
light/phosphor-logo-light: 256 x 256.00004
light/sliders-light: 256.00098 x 256.00098
regular/chat-centered-text: 256.00098 x 256.00098
regular/chat-centered-dots: 256.00098 x 256.00098
regular/chat-centered: 256.00098 x 256.00098
regular/chat-dots: 256.00098 x 256.00098
regular/chat: 256.00098 x 256.00098
regular/chat-text: 256.00098 x 256.00098
regular/chats: 256.00098 x 256.00098
regular/copy-simple: 255.99316 x 255.99316
regular/copy: 255.99316 x 255.99316
regular/crop: 255.99316 x 255.99316
regular/dribbble-logo: 256.01172 x 256
regular/eraser: 256.00098 x 256
regular/faders: 256.00098 x 256.00098
regular/gear-six: 256.00098 x 256.00098
regular/gear: 256.00098 x 256.00098
regular/intersect: 256.00098 x 256.00098
regular/magnifying-glass-minus: 256.00098 x 256.00098
regular/magnifying-glass-plus: 256.00098 x 256.00098
regular/magnifying-glass: 256.00098 x 256.00098
regular/medium-logo: 256.01172 x 256
regular/phosphor-logo: 256 x 256.00004
regular/sliders: 256.00098 x 256.00098
thin/chat-centered-dots-thin: 256.00098 x 256.00098
thin/chat-centered-text-thin: 256.00098 x 256.00098
thin/chat-centered-thin: 256.00098 x 256.00098
thin/chat-dots-thin: 256.00098 x 256.00098
thin/chat-text-thin: 256.00098 x 256.00098
thin/chat-thin: 256.00098 x 256.00098
thin/chats-thin: 256.00098 x 256.00098
thin/copy-thin: 255.99316 x 255.99316
thin/copy-simple-thin: 255.99316 x 255.99316
thin/crop-thin: 255.99316 x 255.99316
thin/eraser-thin: 256.00098 x 256
thin/faders-thin: 256.00098 x 256.00098
thin/gear-six-thin: 256.00098 x 256.00098
thin/gear-thin: 256.00098 x 256.00098
thin/intersect-thin: 256.00098 x 256.00098
thin/magnifying-glass-plus-thin: 256.00098 x 256.00098
thin/magnifying-glass-minus-thin: 256.00098 x 256.00098
thin/magnifying-glass-thin: 256.00098 x 256.00098
thin/phosphor-logo-thin: 256 x 256.00004
thin/sliders-thin: 256.00098 x 256.00098

So looks like there is a bug in SVG export process.

**Comment by rektdeckard** [comment]
Hey @cyberalien thanks for the spot! We did have export issues with Adobe Illustrator, which we handle  during the codegen steps in the React and Vue packages with search-and-replace. I guess I forgot to add that here.

**Comment by rektdeckard** [comment]
Oh hey, I just noticed you run Iconify! Nice work there! Would you consider adding us to your list?

**Comment by cyberalien** [comment]
Thanks!

Yes, adding your really cool icon set is the plan. It will require some tweaks (see https://github.com/iconify/iconify-figma/issues/22#issuecomment-720156670), which I've added in last few days, so it is good to go.

Would it be safe to just automatically replace width/height and viewBox with 256?

**Comment by rektdeckard** [comment]
Perfectly safe. If you feel like making that change, it would be much appreciated as a PR on this repo. Otherwise I'll probably do it over the weekend.
