### ISSUE TITLE
Top indent of the font

### ISSUE THREAD

**Issue by dnavalny** [phosphor-icons/phosphor-icons#4]
All icons have top indent (5px or so) after 2.0 update. 
![image](https://user-images.githubusercontent.com/64607085/100594017-93fa1480-3312-11eb-84d6-f60e08ddfbb7.png)
![image](https://user-images.githubusercontent.com/64607085/100594050-9e1c1300-3312-11eb-82f3-3529eacaa9fd.png)

**Comment by rektdeckard** [comment]
We raised the baseline in `v1.1.0` to have a better out-of-box experience when placed inline next to most fonts, but I honestly regret that decision now 😅. Better to just center the icon in its box and let the user deal with aligning it. I'll try to push a patch on that today.

**Comment by rektdeckard** [comment]
Should be fixed with `v1.1.3`. Let me know if that works as expected.
