### ISSUE TITLE
`display: inline-flex` removed from icon class in 1.4.0

### ISSUE THREAD

**Issue by fjolne** [phosphor-icons/phosphor-icons#6]
In 1.4.0 `display: inline-flex` has been removed from the icon class, which leads to noticable changes in codebases which relied on it being present.

1.3.0:
![image](https://user-images.githubusercontent.com/42907266/147264396-47899a87-0817-4d2d-b921-2f8342203483.png)

1.4.0:
![image](https://user-images.githubusercontent.com/42907266/147264320-13c95d3f-d187-421a-8e0f-50e1e91f5f3d.png)

**Comment by rektdeckard** [comment]
Thanks for spotting, @fjolne. This has been hotfixed in v1.4.1!

**Comment by fjolne** [comment]
@rektdeckard Thanks! Unfortunately, `index.js` still loads 1.4.0 CSS file:
https://github.com/phosphor-icons/phosphor-icons/blob/master/src/index.js

**Comment by rektdeckard** [comment]
Apologies for that. Build scripts are a bit broken after we moved over to using Nucleo to build our icon font :sweat:. Appears to be truly fixed in `1.4.2`. This is why I shouldn't push updates right before going on vacation!

**Comment by fjolne** [comment]
No problem at all, OSS is hard! Thank you for your work and happy holidays ❤️
