### ISSUE TITLE
<noscript> support

### ISSUE THREAD

**Issue by chilledtonic** [phosphor-icons/phosphor-icons#8]
I try to build my websites as compatible as possible for those who don't use client-side javascript;

I could embed all the SVGs I intend to use independently, but this is a major time consumer.

Feather Icons implements using an svg "sprite sheet" which allows me to embed icons as so:
```
<svg
  width="24"
  height="24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <use href="path/to/feather-sprite.svg#circle"/>
</svg>
```

As far as I can tell, phosphor doesn't have a similar SVG available for use - just each icon as an individual file.

I'm curious if such an implementation could be added - or does the Phosphor team have another, more preferred way of embedding these icons script-less? Thanks.

**Comment by chilledtonic** [comment]
Ligatures seem to fix this issue.

**Comment by rektdeckard** [comment]
This lib is based on web fonts, and can be used in a `<noscript>` environment by loading the stylesheets for the weights you need via CDN:

```html
<!DOCTYPE html>
<html>
  <head>
    <link
      rel="stylesheet"
      type="text/css"
      href="https://unpkg.com/@phosphor-icons/web@2.0.1/src/bold/style.css"
    />
  </head>
  <body>
    <i class="ph-bold ph-smiley"></i>
    <i class="ph-bold ph-heart" style="color: hotpink"></i>
    <i class="ph-bold ph-cube"></i>
  </body>
</html>
```
